name: Update Deployment via SSH

on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect SSH & Pulling request
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd public_html && ls -la
          host: noretest.com
          username: u1748803
          port: 65002
          privateKey: ${{ secret.PRIVATE_KEY }}
        env:
          CI: true
